### ISSUE TITLE
Do not set HSTS header

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-profile#54]
We determine globally in OpenConext-deploy which vhosts get HSTS-headers and with what settings. It would help if profile would not send a header of its own (so we don't have to remove it).

This probably boils down to removing from `app/config/config.yml`:
```yaml
nelmio_security:
    …
    forced_ssl:
        hsts_max_age: 2592000 # 30 days
        hsts_subdomains: true
```
